services:
  - type: web
    name: vqa-backend
    env: python
    plan: free
    rootDir: WebApp/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
